### ISSUE TITLE
IllegalStateException thrown after recomposing root composition with subcomposition

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow-kotlin-compose#43]
In the NestedRenderings sample, if you add two children (so one is a legacy view), and then add a child to the non-legacy child, the child will be added but a few milliseconds later an exception will be thrown:
```
    java.lang.IllegalStateException: Expected a group start
        at androidx.compose.SlotReader.assumeGroup(SlotTable.kt:298)
        at androidx.compose.SlotReader.getGroup$compose_runtime_release(SlotTable.kt:43)
        at androidx.compose.Composer.recomposeToGroupEnd(Composer.kt:1363)
        at androidx.compose.Composer.skipCurrentGroup(Composer.kt:1584)
        at androidx.compose.Composer.recompose(Composer.kt:1666)
        at androidx.compose.Recomposer.performRecompose(Recomposer.kt:110)
        at androidx.compose.Recomposer.dispatchRecomposes(Recomposer.kt:142)
        at androidx.compose.AndroidRecomposer$frameCallback$1.doFrame(AndroidRecomposer.kt:39)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:721)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

I'm not sure if this is being thrown by the root composition or the subcomposition. This seems to be a Compose bug, and is a new issue with dev12, it did not occur with dev11.

**Comment by zach-klippenstein** [comment]
Looks like this might have already been fixed on Compose master: https://kotlinlang.slack.com/archives/CJLTWPH7S/p1590801881206400

**Comment by zach-klippenstein** [comment]
Confirmed this works now.
