### ISSUE TITLE
Nested renderings sample crashes on adding first child in dev17

### ISSUE THREAD

**Issue by zach-klippenstein** [square/workflow-kotlin-compose#67]
"Cannot read while a writer is pending"

It worked in dev16. 

<details>
<summary>Stack trace</summary>
<pre>
2020-08-20 00:24:59.577 27660-27660/com.squareup.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.squareup.sample, PID: 27660
    java.lang.IllegalStateException: Cannot read while a writer is pending
        at androidx.compose.runtime.SlotTable.openReader(SlotTable.kt:1162)
        at androidx.compose.runtime.Composer.ambientScopeAt(Composer.kt:2867)
        at androidx.compose.runtime.Composer.access$ambientScopeAt(Unknown Source:0)
        at androidx.compose.runtime.Composer$CompositionReferenceImpl.getAmbientScope$runtime_release(Composer.kt:2300)
        at androidx.compose.runtime.Composer.startRoot(Composer.kt:501)
        at androidx.compose.runtime.Composer.composeInitial(Composer.kt:1849)
        at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:243)
        at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:110)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.kt:262)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Unknown Source:3)
        at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.kt:497)
        at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.kt:254)
        at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.kt:303)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.kt:258)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Unknown Source:3)
        at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.kt:545)
        at android.view.View.dispatchAttachedToWindow(View.java:19553)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3430)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5149)
        at android.view.ViewGroup.addView(ViewGroup.java:4935)
        at android.view.ViewGroup.addView(ViewGroup.java:4875)
        at android.view.ViewGroup.addView(ViewGroup.java:4848)
        at androidx.compose.ui.platform.AndroidComposeView.addAndroidView(AndroidComposeView.kt:284)
        at androidx.compose.ui.node.ViewInteropKt$toLayoutNode$2.invoke(ViewInterop.kt:117)
        at androidx.compose.ui.node.ViewInteropKt$toLayoutNode$2.invoke(Unknown Source:3)
        at androidx.compose.ui.node.LayoutNode.attach(LayoutNode.kt:318)
        at androidx.compose.ui.node.LayoutNode.attach(LayoutNode.kt:312)
        at androidx.compose.ui.node.LayoutNode.insertAt(LayoutNode.kt:216)
        at androidx.compose.ui.node.UiApplier.up(UiApplier.kt:111)
        at androidx.compose.runtime.Composer$realizeInsertUps$1.invoke(Composer.kt:2025)
        at androidx.compose.runtime.Composer$realizeInsertUps$1.invoke(Unknown Source:9)
        at androidx.compose.runtime.Composer.applyChanges(Composer.kt:708)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:262)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Unknown Source:0)
        at androidx.compose.runtime.Recomposer$recomposeAndApplyChanges$3.invoke(Recomposer.kt:195)
        at androidx.compose.runtime.Recomposer$recomposeAndApplyChanges$3.invoke(Unknown Source:7)
        at androidx.compose.runtime.dispatch.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.kt:34)
        at androidx.compose.runtime.dispatch.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.kt:111)
        at androidx.compose.runtime.dispatch.AndroidUiDispatcher.access$performFrameDispatch(Unknown Source:0)
        at androidx.compose.runtime.dispatch.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.kt:71)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
2020-08-20 00:24:59.577 27660-27660/com.squareup.sample E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:721)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
</pre>
</details>

**Comment by zach-klippenstein** [comment]
Appeared in dev17, but still happening on 1.0.0-alpha01.

Seems like a Compose bug, tracked here: https://issuetracker.google.com/issues/166482486

**Comment by zach-klippenstein** [comment]
Leland gave us a fix in [Slack](https://kotlinlang.slack.com/archives/CJLTWPH7S/p1598477281267900?thread_ts=1598475204.265800&cid=CJLTWPH7S).
